const { Configuration, OpenAIApi } = require("openai");
const fs = require('fs');
const key = "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";
module.exports = {
  name: "dalle",
  alias:["dallai","dall-e","dall"],
  desc: "Measures network speed and sends it to the user.",
  react : "🌌",
  category : "Misc",
  usage : "MOVIE <NAME>",
    start: async (Miku,m,{text,args}) => {
var argtoprompt = args.join(" ");
if(!args[0]){
    m.reply("🌐 Please add a query for Generation \n _example : \n.dalle a large cat looking at the sky , high details _");
return;
}
        const configuration = new Configuration({
            apiKey: key
        });
        const openai = new OpenAIApi(configuration);
        m.reply(`_*🖼 Generating Image*_`)
        const predict = async function () {
            const response = await openai.createImage({
                prompt: `${argtoprompt}`,
                n: 1 ,
                size: "1024x1024",
                response_format: 'b64_json',
            });
        
            return response.data;
        }
        m.reply("*🖼 Sending Image From Dall-E Ai*")
        predict()
            .then(
                response => {
                    const now = Date.now();
                    for (let i = 0; i < 1; i++)
                    {const b64 = response.data[i]['b64_json'];
                    const buffer = Buffer.from(b64, "base64");
                    const filename = `image_fromdalle.png`;
                    var argtotext = args.join(" ");
                    Miku.sendMessage(m.from,{image:{url:`${filename}`},caption:`_🖼 *Image Generated by Dall-E Ai | NOVA MD Bot*_\n\n🎛 _Query : ${argtotext}_`},{quoted:m});
                    console.log("Writing image " + filename);
                    fs.writeFileSync(`${filename}`, buffer);
                    console.log(`file saved : ${filename}`);
                    
                    
                    
                    }
                }
            )
  }
}